[package]
name = "neural-combinators"
version = "0.1.0"
authors = ["n-arms <75282394+n-arms@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
